#active spring  boot profile
spring :
   profiles:
      active: dev

---
#common spring boot configuration




---
# dev profile spring boot configuration
spring:
   profiles: dev





---
# prodution profile spring boot configuration
spring:
   profiles: prodution


---
#server